// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaRedeWork.Data;

#nullable disable

namespace SistemaRedeWork.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20241113171755_InitialNewData")]
    partial class InitialNewData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaRedeWork.Models.ArquivoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_CURRICULO");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Dados")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("DADOS");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("ID_ESTUDANTE")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ID_ESTUDANTE");

                    b.ToTable("ARQUIVOS");
                });

            modelBuilder.Entity("SistemaRedeWork.Models.CadastrarVagasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_VAGA");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beneficios")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("BENEFICIOS");

                    b.Property<DateTime>("DataLimiteCandidatura")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_LIMITE");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("DuracaoProjeto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DURACAO_PROJETO");

                    b.Property<decimal>("FaixaSalarialMax")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("MAX_SALARIAL");

                    b.Property<decimal>("FaixaSalarialMin")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("MIN_SALARIAL");

                    b.Property<int>("ID_EMPRESA")
                        .HasColumnType("int")
                        .HasColumnName("ID_EMPRESA");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("LOCALIZACAO");

                    b.Property<string>("ModalidadeContratacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MODALIDADE_CONTRATO");

                    b.Property<string>("NivelExperiencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NIVEL_EXPERIENCIA");

                    b.Property<string>("Requisitos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("REQUISITOS");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS");

                    b.Property<string>("TipoTrabalho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TIPO_TRABALHO");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.HasIndex("ID_EMPRESA");

                    b.ToTable("CADASTRAR_VAGAS");
                });

            modelBuilder.Entity("SistemaRedeWork.Models.CurriculoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_CURRICULO");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CURSO");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_NASC");

                    b.Property<string>("Educacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("EDUCACAO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Experiencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("EXPERIENCIA");

                    b.Property<string>("Habilidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("HABILIDADE");

                    b.Property<int>("ID_ESTUDANTE")
                        .HasColumnType("int");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IDIOMA");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NOME");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("OBJETIVO");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PERIODO");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("SEMESTRE");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TELEFONE");

                    b.Property<string>("Universidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UNIVERSIDADE");

                    b.HasKey("Id");

                    b.HasIndex("ID_ESTUDANTE")
                        .IsUnique();

                    b.ToTable("CURRICULO");
                });

            modelBuilder.Entity("SistemaRedeWork.Models.EmpresaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_EMPRESA");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CEP");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CIDADE");

                    b.Property<string>("ConfirmarSenha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CONFIRMAR_SENHA");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ESTADO");

                    b.Property<string>("Linkedin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("LINKEDIN");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NUMERO");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("RUA");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("SENHA");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("SITE");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TELEFONE");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("USUARIO");

                    b.HasKey("Id");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("SistemaRedeWork.Models.EstudanteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTUDANTE");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CEP");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CPF");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CIDADE");

                    b.Property<string>("ConfirmarSenha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CONFIRMAR_SENHA");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_NASC");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<int?>("EmpresaModelId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ESTADO");

                    b.Property<int>("ID_CURRICULO")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NUMERO");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("LOGRADOURO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("SENHA");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("GENERO");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TELEFONE");

                    b.Property<string>("nomeCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaModelId");

                    b.ToTable("Estudantes", (string)null);
                });

            modelBuilder.Entity("SistemaRedeWork.Models.LoginEmpresaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .HasColumnType("longtext")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("EMAIL");

                    b.Property<int?>("ID_EMPRESA")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("SENHA");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("longtext")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("REMEMBER_ME");

                    b.Property<string>("ResetCode")
                        .HasColumnType("longtext")
                        .HasColumnName("RESET_CODE");

                    b.Property<DateTime?>("ResetCodeExpiration")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("RESET_CODE_EXPIRATION");

                    b.HasKey("Id");

                    b.HasIndex("ID_EMPRESA");

                    b.ToTable("LoginEmpresas");
                });

            modelBuilder.Entity("SistemaRedeWork.Models.LoginEstudanteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("EMAIL");

                    b.Property<int?>("ID_ESTUDANTE")
                        .HasColumnType("int");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("REMEMBER_ME");

                    b.Property<string>("ResetCode")
                        .HasColumnType("longtext")
                        .HasColumnName("RESET_CODE");

                    b.Property<DateTime?>("ResetCodeExpiration")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("RESET_CODE_EXPIRATION");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("SENHA");

                    b.HasKey("Id");

                    b.HasIndex("ID_ESTUDANTE");

                    b.ToTable("LOGIN_ESTUDANTE");
                });

            modelBuilder.Entity("SistemaRedeWork.Models.ArquivoModel", b =>
                {
                    b.HasOne("SistemaRedeWork.Models.EstudanteModel", "Estudante")
                        .WithMany("Arquivos")
                        .HasForeignKey("ID_ESTUDANTE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudante");
                });

            modelBuilder.Entity("SistemaRedeWork.Models.CadastrarVagasModel", b =>
                {
                    b.HasOne("SistemaRedeWork.Models.EmpresaModel", "Empresa")
                        .WithMany("Vagas")
                        .HasForeignKey("ID_EMPRESA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SistemaRedeWork.Models.CurriculoModel", b =>
                {
                    b.HasOne("SistemaRedeWork.Models.EstudanteModel", "Estudante")
                        .WithOne("Curriculo")
                        .HasForeignKey("SistemaRedeWork.Models.CurriculoModel", "ID_ESTUDANTE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudante");
                });

            modelBuilder.Entity("SistemaRedeWork.Models.EstudanteModel", b =>
                {
                    b.HasOne("SistemaRedeWork.Models.EmpresaModel", null)
                        .WithMany("Estudantes")
                        .HasForeignKey("EmpresaModelId");
                });

            modelBuilder.Entity("SistemaRedeWork.Models.LoginEmpresaModel", b =>
                {
                    b.HasOne("SistemaRedeWork.Models.EmpresaModel", "Empresa")
                        .WithMany()
                        .HasForeignKey("ID_EMPRESA");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SistemaRedeWork.Models.LoginEstudanteModel", b =>
                {
                    b.HasOne("SistemaRedeWork.Models.EstudanteModel", "Estudante")
                        .WithMany()
                        .HasForeignKey("ID_ESTUDANTE");

                    b.Navigation("Estudante");
                });

            modelBuilder.Entity("SistemaRedeWork.Models.EmpresaModel", b =>
                {
                    b.Navigation("Estudantes");

                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("SistemaRedeWork.Models.EstudanteModel", b =>
                {
                    b.Navigation("Arquivos");

                    b.Navigation("Curriculo");
                });
#pragma warning restore 612, 618
        }
    }
}
